version: "3"

services:
  api:
    container_name: '${CONTAINER}-api'
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      # Only will build development stage from our dockerfile
      target: development
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "yarn && yarn start:dev"
    ports:
      - '${API_PORT_DEV}:${API_PORT_DEV}'
      - 9229:9229
    environment:
      WAIT_HOSTS: mysql:${DATABASE_PORT}

  mysql:
    container_name: '${CONTAINER}-mysql'
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysqlconfig:/etc/mysql/conf.d
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'

  phpmyadmin:
    container_name: '${CONTAINER}-phpmyadmin'
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
    ports:
      - '${PHP_MYADMIN_PORT}:${PHP_MYADMIN_PORT}'
    depends_on:
      - mysql

volumes:
  mysqldata: {}
