version: "3.8"

services:
  api:
    container_name: '${CONTAINER_NAME}-api'
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app/
    environment:
      NODE_ENV: production
